# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  identifier = "solutions"
  name = "Solutions"
  url = "/solutions"
  weight = 10
  
[[main]]
  name = "Overview"
  parent = "solutions"
  url = "/solutions"
  weight = 1

[[main]]
  name = "Consulting"
  parent = "solutions"
  url = "/consulting"
  weight = 10

[[main]]
  name = "Services"
  parent = "solutions"
  url = "/services"
  weight = 20

#[[main]]
#  parent = "solutions"
#  name = "Products"
#  url = "/products"
#  weight = 30

[[main]]
  name = "Posts"
  url = "/post"
  weight = 20

[[main]]
  identifier = "kb"
  name = "Knowledgebase"
  url = "/docs"
  weight = 30

# [[main]]
#   identifier = "opl"
#   name = "Open Practice Library"
#   url = "/opl"
#   weight = 40

# [[main]]
#   name = "Overview"
#   parent = "opl"
#   url = "/opl"
#   weight = 1

# [[main]]
#   name = "Persepectives"
#   parent = "opl"
#   url = "/opl/perspective"
#   weight = 10

# [[main]]
#   name = "Practice"
#   parent = "opl"
#   url = "/opl/practice"
#   weight = 20

# [[main]]
#   name = "Contributing"
#   parent = "opl"
#   url = "/opl/contributing"
#   weight = 30

# [[main]]
#   name = "About"
#   parent = "opl"
#   url = "/opl/about.html"
#   weight = 40

[[main]]
  name = "About"
  url = "/about"
  weight = 90

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 99

